### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Nussthi** [divtec-cejef/2019-JCO-BulletHell#1]
- [x] Créer un projet git
- [x] Reprendre le gameframework
- [x] Ajuster la taille des fenêtres du projet
- [x] Ajouter un joueur par héritage 
- [x] Ajouter un ennemi par héritage
- [ ] Faire que l'ennemi se déplace
- [ ] Créer un projectile
- [ ] Faire que l'ennemi et le joueur puisse tirer le projectile
